# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='send',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=150)),
                ('sender', models.CharField(max_length=15)),
                ('time_sent', models.TimeField(verbose_name='time sent')),
            ],
        ),
    ]
