# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_send_time_sent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='send',
        ),
    ]
