# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_delete_send'),
    ]

    operations = [
        migrations.CreateModel(
            name='send',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=150)),
                ('sender', models.CharField(max_length=15)),
            ],
        ),
    ]
