# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send',
            name='message',
            field=models.CharField(max_length=2000),
        ),
    ]
