# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20170920_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send',
            name='sender',
            field=models.CharField(max_length=100),
        ),
    ]
